services:
  # Backend service to return LLM output
  backend:
    build: .
    command: gunicorn -b 0.0.0.0:8000 app:app
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}